export async function getServerSideProps({ res }) {
  const base = process.env.NEXT_PUBLIC_URL || 'https://vpntestet.vercel.app';
  const pages = [{"path":"","priority":"1.0","changefreq":"daily"},{"path":"/om-oss","priority":"0.5","changefreq":"monthly"},{"path":"/kontakt","priority":"0.4","changefreq":"monthly"},{"path":"/integritetspolicy","priority":"0.3","changefreq":"yearly"},{"path":"/streaming","priority":"0.8","changefreq":"weekly"},{"path":"/torrenting","priority":"0.8","changefreq":"weekly"},{"path":"/mobil","priority":"0.8","changefreq":"weekly"},{"path":"/gratis","priority":"0.8","changefreq":"weekly"},{"path":"/billigast","priority":"0.8","changefreq":"weekly"},{"path":"/jamfor/expressvpn-vs-nordvpn","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/expressvpn-vs-cyberghost","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/expressvpn-vs-surfshark","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/expressvpn-vs-private-internet-access","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/expressvpn-vs-protonvpn","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/expressvpn-vs-vyprvpn","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/nordvpn-vs-cyberghost","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/nordvpn-vs-surfshark","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/nordvpn-vs-private-internet-access","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/nordvpn-vs-protonvpn","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/nordvpn-vs-vyprvpn","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/cyberghost-vs-surfshark","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/cyberghost-vs-private-internet-access","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/cyberghost-vs-protonvpn","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/cyberghost-vs-vyprvpn","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/surfshark-vs-private-internet-access","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/surfshark-vs-protonvpn","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/surfshark-vs-vyprvpn","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/private-internet-access-vs-protonvpn","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/private-internet-access-vs-vyprvpn","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/protonvpn-vs-vyprvpn","priority":"0.7","changefreq":"weekly"}];
  const xml = '<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' +
    pages.map(function(p) { return '<url><loc>'+base+p.path+'</loc><lastmod>2026-06-24</lastmod><changefreq>'+p.changefreq+'</changefreq><priority>'+p.priority+'</priority></url>'; }).join('') +
    '</urlset>';
  res.setHeader('Content-Type', 'application/xml');
  res.setHeader('Cache-Control', 's-maxage=86400, stale-while-revalidate');
  res.write(xml); res.end();
  return { props: {} };
}
export default function Sitemap() { return null; }